#进群欢迎消息 可自行更改 更改后重启机器人
joinMessage: "欢迎进群"
#退群消息 {0} 代表退群QQ号
levelMessage: "{0} 退群了"
#禁言时间 分钟
time: 15
#敏感词列表 如果他里面包含了这个词语就禁言 禁言多少分钟自行配置
punish:
  - "傻逼"
  - "sb"
#启用的群
gourps:
  - "798432337"
#机器人管理
owner:
  - "2256360521"
  - "1029956612"
  - "2994870391"
  - "1919041509"
  - "3119009051"
